Client:
    type: entity
    table: client
    uniqueConstraints:
        client_login_key:
            columns:
                - login
        client_email_key:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        login:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        nom:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        prenom:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        password:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
    lifecycleCallbacks: {  }
